### ISSUE TITLE
툿을 게시할때마다 Vim 레이아웃이 깨지는 문제가 발생함.

### ISSUE THREAD

**Issue by malkoG** [kode-team/mastodon.nvim#1]
# 재현 방법

![Deepin스크린샷_선택 영역_20221115135859](https://user-images.githubusercontent.com/2427963/201845406-9aa3d801-1617-45ae-89c0-5e14dbe38d3b.png)

`:TootMessage "<메세지 내용>"` 명령을 실행하기만 하면 됨.

# 문제의 원인

툿을 게시할때마다 내부적으로 curl 을 쓰고 있는데,
curl로 날린 요청이 어떻게 진행되고 있는지 현황을 알려주는 텍스트 때문에 Vim의 레이아웃이 한번에 깨지는 문제가 발생합니다.

이런 문제를 어떻게 해결하는 것이 좋을까요?

문제의 핵심이 되는 코드는 여기입니다. https://github.com/kode-team/mastodon.nvim/blob/main/lua/mastodon/commands.lua#L19-L38

**Comment by IAOON** [comment]
curl에 옵션을 붙이면 안 되려나요?
(`-s`나 `-v` 같은 걸 붙여서 progress를 출력 안 하게 할 수도 있을 것 같은데, 되는 지는 잘 모르겠네요.)

-s, --silent

Silent or quiet mode. Do not show progress meter or error messages. Makes Curl mute. It will still output the data you ask for, potentially even to the terminal/stdout unless you redirect it.

Use [-S, --show-error](https://curl.se/docs/manpage.html#-S) in addition to this option to disable progress meter but still show error messages.

Providing [-s, --silent](https://curl.se/docs/manpage.html#-s) multiple times has no extra effect. Disable it again with --no-silent.

Example:

 curl -s https://example.com
See also [-v, --verbose](https://curl.se/docs/manpage.html#-v), [--stderr](https://curl.se/docs/manpage.html#--stderr) and [--no-progress-meter](https://curl.se/docs/manpage.html#--no-progress-meter).

참조 : https://curl.se/docs/manpage.html#-q

**Comment by malkoG** [comment]
덕분에 해결했습니다. 감사합니다.
