### ISSUE TITLE
Need installation guide for lazy.nvim users

### ISSUE THREAD

**Issue by malkoG** [kode-team/mastodon.nvim#20]
**lazy.nvim** is new package manager for neovim made by **folke**.
It has been released since 2022-12-22. But, it's user has been increasing incredibly fast. 

According to https://github.com/folke/lazy.nvim, the number of star is over 1,000 within few days!

Not just for packer.nvim, we need to prepare installation guide for lazy.nvim

**Comment by kimusan** [comment]
``` 
{
  "kode-team/mastodon.nvim",
  dependencies = {
    "nvim-lua/plenary.nvim",
    "rcarriga/nvim-notify",
    "kkharji/sqlite.lua",
  },
  config = function()
    require("mastodon").setup()
  end
}
```

**Comment by malkoG** [comment]
@kimusan Thanks for sharing your configuration! 🙇
